use crate::{cil_tree::{cil_node::CILNode, CILTree}, r#type::Type, IString};

use super::AssemblyExporter;
use std::{borrow::Cow, io::Write};
pub struct CExporter {
    types:Vec<u8>,
    type_defs:Vec<u8>,
    method_defs:Vec<u8>,
    encoded_asm: Vec<u8>,
    headers:Vec<u8>,
}
impl std::io::Write for CExporter {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.encoded_asm.write(buf)
    }
    fn flush(&mut self) -> std::io::Result<()> {
        self.encoded_asm.flush()
    }
}
impl CExporter{
    fn as_source(&self)->Vec<u8>{
        let mut res = self.headers.clone();
        res.extend(&self.types);
        res.extend(&self.type_defs);
        res.extend(&self.method_defs);
        res.extend(&self.encoded_asm);
      
        res
    }
}
impl AssemblyExporter for CExporter {
    fn init(asm_info: &super::AssemblyInfo) -> Self {
        let encoded_asm = Vec::with_capacity(0x1_00);
        let types = Vec::with_capacity(0x1_00);
        let type_defs = Vec::with_capacity(0x1_00);
        let method_defs = Vec::with_capacity(0x1_00);
        let mut headers = Vec::with_capacity(0x1_00);
        write!(headers, "// This file was autogenerated by `rustc_codegen_clr` by FractalFir\n // It contains C code made from Rust.\n").expect("Write error!");
        write!(headers, "#include  <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n").expect("Write error!");
        Self {
            types,
            type_defs,
            encoded_asm,
            method_defs,
            headers
        }
    }
    fn add_type(&mut self, tpe: &crate::r#type::TypeDef) {
        let name = tpe.name();
        let mut fields = String::new();
        for (field_name, field_type) in tpe.fields() {
            fields.push_str(&format!("{field_type} {field_name};", field_type = c_tpe(field_type)));
         
        }
        println!("Ingoring field layout FOR NOW");
        write!(self.types,"typedef struct {name} {name};\n").unwrap();
        write!(self.type_defs,"struct {name}{{\n{fields}}};\n").unwrap()
    }

    fn add_method(&mut self, method: &crate::method::Method) {
        //eprintln!("C source:\n{}",String::from_utf8_lossy(&self.as_source()));
        let sig = method.sig();
        
        let name = method.name();
        let output = c_tpe(sig.output());
        let mut inputs:String = "(".into();
        let mut input_iter = sig.inputs().iter().enumerate();
        if let Some((idx,input)) = input_iter.next() {
            inputs.push_str(&format!("{input} A{idx}",input = c_tpe(input)));
        }
        for (idx,input) in input_iter {
            inputs.push_str(&format!(",{input} A{idx} ",input = c_tpe(input)));
        }
        inputs.push(')');
        let mut code = String::new();
        for (id,(_,local)) in method.locals().iter().enumerate(){
            if *local == Type::Void{
                continue;
            }
            code.push_str(&format!("\t{local} L{id};\n",local = c_tpe(local)));
        }
        for bb in method.blocks(){
            code.push_str(&format!("\tBB_{}:\n",bb.id()));
            for tree in bb.trees(){
                code.push_str(&format!("{}\n",tree_string(tree)));
            }
        }
        write!(self.method_defs,"{output} {name} {inputs};\n").unwrap();
        write!(self.encoded_asm,"{output} {name} {inputs}{{\n{code}}}\n").unwrap();
        std::fs::File::create("/home/michal/test.c").unwrap().write_all(&self.as_source()).unwrap();
    }

    fn add_extern_method(&mut self, lib_path: &str, name: &str, sig: &crate::function_sig::FnSig) {
        todo!()
    }

    fn finalize(self, final_path: &std::path::Path, is_dll: bool) -> Result<(), super::AssemblyExportError> {
        todo!()
    }

    fn add_extern_ref(&mut self, asm_name: &str, info: &crate::assembly::AssemblyExternRef) {
        // Not needed in C
    }

    fn add_global(&mut self, tpe: &crate::r#type::Type, name: &str) {
        eprintln!("C source:\n{}",String::from_utf8_lossy(&self.as_source()));
        todo!()
    }
}
fn node_string(tree: &CILNode) -> String {
    match tree{
        CILNode::LDLoc(loc) =>format!("L{loc}"),
        CILNode::LDArg(arg) => format!("A{arg}"),
        CILNode::LDLocA(arg) => format!("((size_t)(void*)&L{arg})"),
        CILNode::LDArgA(loc) => format!("((size_t)(void*)&A{loc})"),
        CILNode::BlackBox(inner) =>node_string(inner),
        CILNode::LDStaticField(_) => todo!(),
        CILNode::ConvF32(inner) => format!("((float){inner})",inner = node_string(inner)),
        CILNode::ConvF64(inner)  => format!("((double){inner})",inner = node_string(inner)),
        CILNode::ConvF64Un(_) => todo!(),
        CILNode::SizeOf(_) => todo!(),
        CILNode::LDIndI8 { ptr } => format!("(*((uint8_t*){ptr}))",ptr = node_string(ptr)),
        CILNode::LDIndI16 { ptr } => todo!(),
        CILNode::LDIndI32 { ptr } => todo!(),
        CILNode::LDIndI64 { ptr } => todo!(),
        CILNode::LDIndISize { ptr } => todo!(),
        CILNode::LdObj { ptr, obj } => todo!(),
        CILNode::LDIndF32 { ptr } => todo!(),
        CILNode::LDIndF64 { ptr } => todo!(),
        CILNode::LDFieldAdress { addr, field } => todo!(),
        CILNode::LDField { addr, field } => todo!(),
        CILNode::Add(a, b) =>format!("{a} + {b}",a = node_string(a),b = node_string(b)),
        CILNode::And(_, _) => todo!(),
        CILNode::Sub(_, _) => todo!(),
        CILNode::Mul(_, _) => todo!(),
        CILNode::Div(_, _) => todo!(),
        CILNode::Rem(_, _) => todo!(),
        CILNode::RemUn(_, _) => todo!(),
        CILNode::Or(_, _) => todo!(),
        CILNode::XOr(_, _) => todo!(),
        CILNode::Shr(_, _) => todo!(),
        CILNode::Shl(_, _) => todo!(),
        CILNode::ShrUn(_, _) => todo!(),
        CILNode::RawOpsParrentless { ops } => todo!(),
        CILNode::Call { args, site } => {
            let name = site.name();
            let mut input_iter = args.iter();
            let mut inputs:String = "(".into();
            if let Some(input) = input_iter.next() {
                inputs.push_str(&format!("{input}",input = node_string(input)));
            }
            for input in input_iter {
                inputs.push_str(&format!(",{input} ",input = node_string(input)));
            }
            inputs.push(')');
            format!("{name}{inputs}")
        }
        CILNode::CallVirt { args, site } => todo!(),
        CILNode::LdcI64(value) => format!("{value}l"),
        CILNode::LdcU64(value) => format!("{value}ul"),
        CILNode::LdcI32(value) =>format!("{value}"),
        CILNode::LdcU32(value) =>  format!("{value}u"),
        CILNode::LdcF64(value) => format!("{value}"),
        CILNode::LdcF32(value) => format!("{value}"),
        CILNode::LoadGlobalAllocPtr { alloc_id } => todo!(),
        CILNode::ConvU8(inner) => format!("((uint8_t){inner})",inner = node_string(inner)),
        CILNode::ConvU16(inner) => format!("((uint16_t){inner})",inner = node_string(inner)),
        CILNode::ConvU32(inner) =>format!("((uint32_t){inner})",inner = node_string(inner)),
        CILNode::ConvU64(inner) =>format!("((uint64_t){inner})",inner = node_string(inner)),
        CILNode::ConvUSize(inner) => format!("((size_t){inner})",inner = node_string(inner)),
        CILNode::ConvI8(_) => todo!(),
        CILNode::ConvI16(_) => todo!(),
        CILNode::ConvI32(_) => todo!(),
        CILNode::ConvI64(_) => todo!(),
        CILNode::ConvISize(inner) => format!("((ptrdiff_t){inner})",inner = node_string(inner)),
        CILNode::Neg(_) => todo!(),
        CILNode::Not(_) => todo!(),
        CILNode::Eq(a, b) =>  format!("{a} == {b}",a = node_string(a),b = node_string(b)),
        CILNode::Lt(a, b) |
        CILNode::LtUn(a, b) => format!("{a} < {b}",a = node_string(a),b = node_string(b)),
        CILNode::Gt(a, b) |
        CILNode::GtUn(a, b)=> format!("{a} > {b}",a = node_string(a),b = node_string(b)),
        CILNode::TemporaryLocal(_) => todo!(),
        CILNode::SubTrees(_, _) => todo!(),
        CILNode::LoadAddresOfTMPLocal => todo!(),
        CILNode::LoadTMPLocal => todo!(),
        CILNode::LDFtn(_) => todo!(),
        CILNode::LDTypeToken(_) => todo!(),
        CILNode::NewObj { site, args } =>  {
            let name = site.name();
            let mut input_iter = args.iter();
            let mut inputs:String = "(".into();
            if let Some(input) = input_iter.next() {
                inputs.push_str(&format!("{input}",input = node_string(input)));
            }
            for input in input_iter {
                inputs.push_str(&format!(",{input} ",input = node_string(input)));
            }
            inputs.push(')');
            let tpe_name = site.class().unwrap().name_path();
            format!("ctor_{tpe_name}{inputs}")
        }
        CILNode::LdStr(_) => todo!(),
        CILNode::CallI { sig, fn_ptr, args } => todo!(),
    }
}
fn tree_string(tree: &CILTree) -> String {
    match tree.tree(){
        crate::cil_tree::cil_root::CILRoot::STLoc { local, tree } => format!("\tL{local} = {tree};\n",tree = node_string(tree)),
        crate::cil_tree::cil_root::CILRoot::BTrue { target, sub_target, ops } => {
            assert_eq!(*sub_target,0);
            format!("\tif({ops})goto BB_{target};\n",ops = node_string(ops))
        }
        crate::cil_tree::cil_root::CILRoot::GoTo { target, sub_target } =>format!("goto BB_{target};"),
        crate::cil_tree::cil_root::CILRoot::Call { site, args } => {
            let name = site.name();
            let mut input_iter = args.iter();
            let mut inputs:String = "(".into();
            if let Some(input) = input_iter.next() {
                inputs.push_str(&format!("{input}",input = node_string(input)));
            }
            for input in input_iter {
                inputs.push_str(&format!(",{input} ",input = node_string(input)));
            }
            inputs.push(')');
            format!("{name}{inputs};")
        }
        crate::cil_tree::cil_root::CILRoot::SetField { addr, value, desc } => todo!(),
        crate::cil_tree::cil_root::CILRoot::SetTMPLocal { value } => todo!(),
        crate::cil_tree::cil_root::CILRoot::CpBlk { src, dst, len } => todo!(),
        crate::cil_tree::cil_root::CILRoot::STIndI8(_, _) => todo!(),
        crate::cil_tree::cil_root::CILRoot::STIndI16(_, _) => todo!(),
        crate::cil_tree::cil_root::CILRoot::STIndI32(_, _) => todo!(),
        crate::cil_tree::cil_root::CILRoot::STIndI64(_, _) => todo!(),
        crate::cil_tree::cil_root::CILRoot::STIndISize(_, _) => todo!(),
        crate::cil_tree::cil_root::CILRoot::STIndF64(_, _) => todo!(),
        crate::cil_tree::cil_root::CILRoot::STIndF32(_, _) => todo!(),
        crate::cil_tree::cil_root::CILRoot::STObj { tpe, addr_calc, value_calc } => todo!(),
        crate::cil_tree::cil_root::CILRoot::STArg { arg, tree } => format!("A{arg} = {tree};",tree = node_string(tree)),
        crate::cil_tree::cil_root::CILRoot::Break => "".into(),
        crate::cil_tree::cil_root::CILRoot::Nop => todo!(),
        crate::cil_tree::cil_root::CILRoot::InitBlk { dst, val, count } => todo!(),
        crate::cil_tree::cil_root::CILRoot::CallVirt { site, args } => todo!(),
        crate::cil_tree::cil_root::CILRoot::Ret { tree } => format!("\treturn {ops};",ops = node_string(tree)),
        crate::cil_tree::cil_root::CILRoot::Pop { tree } => format!("\t{ops};",ops = node_string(tree)),
        crate::cil_tree::cil_root::CILRoot::VoidRet => "return;".into(),
        crate::cil_tree::cil_root::CILRoot::Throw(_) => format!("abort();"),
        crate::cil_tree::cil_root::CILRoot::ReThrow => todo!(),
        crate::cil_tree::cil_root::CILRoot::CallI { sig, fn_ptr, args } => todo!(),
        crate::cil_tree::cil_root::CILRoot::JumpingPad { ops } => todo!("There should be no jumping pads in C"),
        crate::cil_tree::cil_root::CILRoot::SetStaticField { descr, value } => todo!(),
    }
}
fn c_tpe(tpe:&Type) -> Cow<'static, str> {
    match tpe{
        Type::Bool => "bool".into(),
        Type::USize => "size_t".into(),
        Type::ISize => "ptrdiff_t".into(),
        Type::Void => "void".into(),
        Type::I128 => "__int128".into(),
        Type::U128 => "unsigned __int128".into(),
        Type::I64 => "int64_t".into(),
        Type::U64 => "uint64_t".into(),
        Type::I32 => "int32_t".into(),
        Type::U32 => "uint32_t".into(),
        Type::F64 => "float".into(),
        Type::F32 => "double".into(),
        Type::I16 => "int16_t".into(),
        Type::U16 => "uint16_t".into(),
        Type::I8 => "int8_t".into(),
        Type::U8 => "uint8_t".into(),
        Type::Ptr(inner)=>format!("{inner}*",inner = c_tpe(inner)).into(),
        Type::DotnetType(tref)=>{
            if tref.asm().is_some(){
                println!("Type {tref:?} is not supported in C");
            }
            tref.name_path().to_owned().into()
        }
        _=>todo!("Unsuported type {tpe:?}")
    }
}