[package]
name = "build_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#mycorrhiza = {path="../../mycorrhiza"}
#rand = "0.8.5"
[workspace]
[profile.release.build-override]
codegen-units = 1
