[package]
name = "rustc_codegen_clr_call"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc_codegen_clr_type = {path = "../rustc_codegen_clr_type"}
rustc_codegen_clr_ctx = {path = "../rustc_codegen_clr_ctx"}
cilly = {path = "../cilly"}